services:
  gateway:
    build: ./gateway-nginx
    container_name: mockpay_gateway
    ports:
      - "8080:80"
    depends_on:
      - account-service
      - payment-service

  account-service:
    build: ./account-service
    container_name: mockpay_account_service
    depends_on:
      - account-db
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@account-db:27017/account_db?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8081
  payment-service:
    build:
      context: ./payment-service/PaymentService
    container_name: mockpay_payment_service
    depends_on:
      - payment-db
      - rabbit-mq
      - queue-setup
    environment:
      - ConnectionStrings__DefaultConnection=Host=payment-db;Port=5432;Database=payment_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASS}
      - ASPNETCORE_URLS=http://+:8082
      - RABBITMQ_USER=${RABBIT_USER}
      - RABBITMQ_PASS=${RABBIT_PASS}
      - RABBITMQ_HOST=rabbit-mq

  webhook-service:
    build:
      context: ./webhook-service
    container_name: mockpay_webhook_service
    ports:
      - "8083:8083" 
    depends_on:
      - rabbit-mq
      - webhook-db
      - queue-setup
    environment:
      - MONGO_URI=mongodb://${MONGO_WEBHOOK_USER}:${MONGO_WEBHOOK_PASS}@webhook-db:27017/webhook_db?authSource=admin
      
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASS=${RABBIT_PASS}
      - RABBITMQ_HOST=rabbit-mq 
      - PORT=8083
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:3.13-management-alpine
    container_name: mockpay_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-mq-data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    restart: unless-stopped
    command: >
      sh -c "
        rabbitmq-plugins enable --offline rabbitmq_management &&
        wget -O /plugins/rabbitmq_delayed_message_exchange.ez https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez &&
        rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange &&
        rabbitmq-server
      "
  queue-setup:
    build:
      context: ./rabbitmq-setup
    depends_on:
      - rabbit-mq
    environment:
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASS=${RABBIT_PASS}
      - RABBITMQ_HOST=rabbit-mq 

  account-db:
    image: mongo:6.0
    container_name: mockpay-account-db
    ports:
      - "27017:27017"
    volumes:
      - account-db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  account-db-admin:
    image: mongo-express
    container_name: mockpay-account-db-admin
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - account-db
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ADMIN_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ADMIN_PASS}

      ME_CONFIG_MONGODB_SERVER: account-db

      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  payment-db:
    image: postgres:15-alpine
    container_name: mockpay_payment_db
    ports:
      - "5432:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=payment_db
    restart: unless-stopped

  webhook-db:
    image: mongo:6.0
    container_name: mockpay_webhook_db
    ports: 
      - "27018:27017"
    volumes:
      - webhook-db-data:/data/db_webhook
    environment:
      # Usa as novas credenciais do .env
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_WEBHOOK_USER} 
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_WEBHOOK_PASS}
      # O nome da base de dados
      - MONGO_INITDB_DATABASE=webhook_db
    restart: unless-stopped
  webhook-db-admin:
    image: mongo-express
    container_name: mockpay-webhook-db-admin
    restart: unless-stopped
    ports:
      - "8089:8081"
    depends_on:
      - webhook-db
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ADMIN_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ADMIN_PASS}

      ME_CONFIG_MONGODB_SERVER: webhook-db

      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_WEBHOOK_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_WEBHOOK_PASS}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

volumes:
  account-db-data:
    driver: local
  payment-db-data:
    driver: local
  rabbit-mq-data:
    driver: local
  webhook-db-data:
    driver: local